version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 57080:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwordStrong2023
    ports:
      - "57081:80"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwordStrong2023
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Mypassword2023
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/mydatabase.sql

